### ISSUE TITLE
ElementInput not found

### ISSUE THREAD

**Issue by cloudstudio** [fat4lix/nova-element-ui#1]
Hello ! thanks for this awesome package.

I think you are missing something in readme.

use ElementInput; or something like this, if not you can't use:

ElementInput::make('Surname')->clearable(),

I get this error : ElementInput not found

Thanks !

**Comment by fat4lix** [comment]
Hello! Did you import component correctly?
use NightKit\NovaElements\Fields\ElementInput\ElementInput;

**Comment by cloudstudio** [comment]
Yep ! , Can you put it in readme to avoid confusion?

Anyway is not working for me :( no error but nothing happend.

Thanks for you time ! appreciate it !

![captura de pantalla 2018-08-25 a las 22 13 04](https://user-images.githubusercontent.com/3589377/44622173-dde22d80-a8b3-11e8-84bb-d3e4614dd0ef.png)
![captura de pantalla 2018-08-25 a las 22 12 51](https://user-images.githubusercontent.com/3589377/44622174-de7ac400-a8b3-11e8-886f-e5f0b486c620.png)

**Comment by cloudstudio** [comment]
Cache, lol, thanks mate !
